$env:DIFY_API_BASE_URL = "http://hdpd.cpolar.cn/v1"
$env:DIFY_API_KEY = "dataset-UMJU8FSM8fdPLu03IXuk13bJ"
$env:DIFY_DATASET_POLICY = "385d9d8d-0d7e-444d-b405-cf7972e7f2c0"
$env:DIFY_DATASET_INTERNAL = "fd284a4a-d394-416b-b246-ab4e036d8904"

Write-Host "Dify 环境变量已写入当前 PowerShell 会话。"
Write-Host "DIFY_API_BASE_URL=$env:DIFY_API_BASE_URL"
Write-Host "DIFY_DATASET_POLICY=$env:DIFY_DATASET_POLICY"
Write-Host "DIFY_DATASET_INTERNAL=$env:DIFY_DATASET_INTERNAL"
Write-Host "DIFY_API_KEY 已设置（为避免泄露，此处不回显）。"
